### ISSUE TITLE
Add option to run auto-sync as one-shot

### ISSUE THREAD

**Issue by DonOregano** [doudou/snapsync#6]
When using systemd timers for scheduling snapsync it would be useful to be able to run it in automatic mode, but only perform one sync.

Running in manual mode has downsides, like having to do manual mounts, etc.

**Comment by doudou** [comment]
Just to be sure that I understand: you mean doing the auto-mount and auto-unmount, but not looping ?

**Comment by DonOregano** [comment]
Yeah, exactly.

So that my systemd timer could just call snapsync auto-sync --once

It would do everything that auto-sync does, except looping.

**Comment by doudou** [comment]
I'll see what I can do ... I have little time these days.

**Comment by doudou** [comment]
https://github.com/doudou/snapsync/releases/tag/v0.3.7 implements `auto-sync --one-shot`
